name: subsonic-analyzer

services:
    analyzer:
        image: subsonic-analyzer:0.0.2
        build:
            tags:
                - "subsonic-analyzer:0.0.2"
            context: .
        ports:
            - 8000:8000
        volumes:
            - ./data:/app/data
