package io.github.defective4.audioanalyzer.app.proxy;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.JsonObject;

import io.github.defective4.audioanalyzer.app.App;
import io.github.defective4.audioanalyzer.ml.Repository;
import io.github.defective4.audioanalyzer.ml.model.Track;
import io.github.defective4.audioanalyzer.subsonic.SubsonicAPI;
import io.github.defective4.audioanalyzer.subsonic.model.Album;
import io.github.defective4.audioanalyzer.subsonic.model.Playlist;
import io.github.defective4.audioanalyzer.subsonic.model.Song;

public class VirtualLibraryManager {
    private static final DateFormat FMT = new SimpleDateFormat("yyyy-MM-ddZ");

    private final Map<String, Map<String, Playlist>> generatedPlaylists = new HashMap<>();
    private final Repository repo;

    private final String targetBaseURL;

    public VirtualLibraryManager(Repository repo, String targetBaseURL) throws MalformedURLException {
        this.repo = repo;
        this.targetBaseURL = URI.create(targetBaseURL).toURL().toString();
    }

    public Map<String, Playlist> generateOrGetPlaylists(SubsonicAPI api, int limit) throws IOException, SQLException {
        String user = api.getUsername();
        if (!generatedPlaylists.containsKey(user)) {
            List<Album> albums = api.getAlbumList(10, 0, "recent");
            List<Song> allSongs = new ArrayList<>();
            for (Album album : albums) allSongs.addAll(api.getMusicDirectory(album.id));

            List<Song> songs = allSongs.stream().sorted((o1, o2) -> {
                long l1 = o1.playCount;
                long l2 = o2.playCount;
                return l1 > l2 ? -1 : l2 > l1 ? 1 : 0;
            }).limit(10).toList();

            List<Track> baseTracks = new ArrayList<>();
            for (Song song : songs) {
                repo.getTrackById(song.id).ifPresent(baseTracks::add);
            }

            List<Track> all = repo.getAllTracks(true);
            List<Track> similarTracks = new ArrayList<>();

            int perTrack = Math.ceilDiv(limit, baseTracks.size());
            for (Track track : baseTracks) {
                similarTracks.addAll(App.sortTrackStream(true, all.stream(), track).limit(perTrack).toList());
            }

            List<JsonObject> similar = new ArrayList<>();
            for (Track track : similarTracks) {
                similar.add(api.getRawSongData(track.id()));
            }

            Playlist fromRecent = new Playlist("virt_recent", "From your recent sessions");
            fromRecent.comment = "Auto-generated by subsonic-analyzer";
            fromRecent.duration = similar.stream()
                    .mapToInt(s -> s.has("duration") ? s.getAsJsonPrimitive("duration").getAsInt() : 0).sum();
            fromRecent.entry = similar.toArray(JsonObject[]::new);
            fromRecent.isPublic = true;
            fromRecent.owner = "subsonic-analyzer";
            fromRecent.songCount = similar.size();

            String date = FMT.format(new Date(System.currentTimeMillis()));
            fromRecent.changed = date;
            fromRecent.created = date;

            generatedPlaylists.put(user, Map.of(fromRecent.id, fromRecent));
        }
        return Collections.unmodifiableMap(generatedPlaylists.get(user));
    }

    public static void main(String[] args) throws Exception {
        VirtualLibraryManager libraryManager = new VirtualLibraryManager(new Repository("jdbc:sqlite:mood.sqlite"),
                "https://music.raspberry.local");
        SubsonicAPI api = new SubsonicAPI("test", "test".toCharArray(), "https://music.raspberry.local");
        libraryManager.generateOrGetPlaylists(api, 30);
    }
}
