package io.github.defective4.audioanalyzer.app.proxy;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import io.github.defective4.audioanalyzer.app.App;
import io.github.defective4.audioanalyzer.ml.Repository;
import io.github.defective4.audioanalyzer.ml.model.Track;
import io.github.defective4.audioanalyzer.ml.mood.CompositeMood;
import io.github.defective4.audioanalyzer.ml.mood.MoodTypes;
import io.github.defective4.audioanalyzer.subsonic.SubsonicAPI;
import io.github.defective4.audioanalyzer.subsonic.model.Album;
import io.github.defective4.audioanalyzer.subsonic.model.Playlist;
import io.github.defective4.audioanalyzer.subsonic.model.Song;

public class VirtualLibraryManager {
    private static final DateFormat FMT = new SimpleDateFormat("yyyy-MM-ddZ");

    private final Map<String, Map<String, Playlist>> generatedPlaylists = new HashMap<>();
    private final Random rand = new Random();

    private final Repository repo;
    private final String targetBaseURL;

    public VirtualLibraryManager(Repository repo, String targetBaseURL) throws MalformedURLException {
        this.repo = repo;
        this.targetBaseURL = URI.create(targetBaseURL).toURL().toString();
    }

    public Map<String, Playlist> generateOrGetPlaylists(SubsonicAPI api, int limit) throws IOException, SQLException {
        String user = api.getUsername();
        if (!generatedPlaylists.containsKey(user)) {
            Playlist recent = generatePlaylistFromRecents(api, limit);
            Playlist study = generateMoodPlaylist(api, limit, MoodTypes.getMood("study"));

            generatedPlaylists.put(user, Map.of(recent.id, recent, study.id, study));
        }
        return Collections.unmodifiableMap(generatedPlaylists.get(user));
    }

    private Playlist generateMoodPlaylist(SubsonicAPI api, int limit, CompositeMood mood)
            throws SQLException, IOException {
        List<Track> allTracks = new ArrayList<>(repo.getAllTracks(true));
        Collections.shuffle(allTracks, rand);
        List<Track> tracks = allTracks.stream().filter(mood::matches).limit(limit).toList();
        return generatePlaylist(api, null, tracks, "virt_study", "Music to study to");
    }

    private Playlist generatePlaylistFromRecents(SubsonicAPI api, int limit) throws IOException, SQLException {
        List<Album> albums = api.getAlbumList(5, 0, "recent");
        List<Song> allSongs = new ArrayList<>();
        for (Album album : albums) allSongs.addAll(api.getMusicDirectory(album.id));

        List<Song> songs = allSongs.stream().sorted((o1, o2) -> {
            long l1 = o1.playCount;
            long l2 = o2.playCount;
            return l1 > l2 ? -1 : l2 > l1 ? 1 : 0;
        }).limit(5).toList();

        List<Track> baseTracks = new ArrayList<>();
        for (Song song : songs) {
            repo.getTrackById(song.id).ifPresent(baseTracks::add);
        }

        List<Track> all = repo.getAllTracks(true);
        List<Track> similarTracks = new ArrayList<>();

        int perTrack = Math.ceilDiv(limit, baseTracks.size());
        for (Track track : baseTracks) {
            similarTracks.addAll(App.sortTrackStream(true, all.stream(), track).limit(perTrack).toList());
        }

        return generatePlaylist(api, albums.get(0).coverArt, similarTracks, "virt_recent", "From your recent sessions");
    }

    public static void main(String[] args) throws Exception {
        VirtualLibraryManager libraryManager = new VirtualLibraryManager(new Repository("jdbc:sqlite:mood.sqlite"),
                "https://music.raspberry.local");
        SubsonicAPI api = new SubsonicAPI("test", "test".toCharArray(), "https://music.raspberry.local");
        libraryManager.generateOrGetPlaylists(api, 30);
    }

    private static Playlist generatePlaylist(SubsonicAPI api, String cover, List<Track> tracks, String id, String name)
            throws IOException {
        List<JsonObject> similar = new ArrayList<>();
        for (Track track : tracks) {
            similar.add(api.getRawSongData(track.id()));
        }

        Playlist fromRecent = new Playlist(id, name);
        fromRecent.comment = "Auto-generated by subsonic-analyzer";
        fromRecent.duration = similar.stream()
                .mapToInt(s -> s.has("duration") ? s.getAsJsonPrimitive("duration").getAsInt() : 0).sum();
        fromRecent.entry = similar.toArray(JsonObject[]::new);
        fromRecent.isPublic = true;
        fromRecent.owner = "subsonic-analyzer";
        fromRecent.songCount = similar.size();

        String date = FMT.format(new Date(System.currentTimeMillis()));
        fromRecent.changed = date;
        fromRecent.created = date;
        if (cover == null && !similar.isEmpty()) {
            JsonElement e = similar.get(0).get("coverArt");
            if (e != null) cover = e.getAsString();
        }
        fromRecent.coverArt = cover;

        return fromRecent;
    }
}
