package io.github.defective4.audioanalyzer.config;

import java.awt.Color;
import java.util.Objects;

import io.github.defective4.audioanalyzer.util.FontAwesomeIcons;

public record ProxyVirtualLibConfig(Boolean enableVirtualLibrary, Boolean generateFromRecents, Integer fromRecentsLimit,
        String fromRecentsIcon, String fromRecentsCoverColor, String fromRecentsName, String fromRecentsIconColor,
        String defaultPlaylistAuthor, String defaultPlaylistDescription, ProxyPlaylistConfig[] playlists) {

    public ProxyVirtualLibConfig(Boolean enableVirtualLibrary, Boolean generateFromRecents, Integer fromRecentsLimit,
            String fromRecentsIcon, String fromRecentsCoverColor, String fromRecentsName, String fromRecentsIconColor,
            String defaultPlaylistAuthor, String defaultPlaylistDescription, ProxyPlaylistConfig[] playlists) {
        this.enableVirtualLibrary = enableVirtualLibrary == null ? true : enableVirtualLibrary;
        this.generateFromRecents = generateFromRecents == null ? true : generateFromRecents;
        this.fromRecentsLimit = fromRecentsLimit == null ? 30 : fromRecentsLimit;
        this.fromRecentsIcon = fromRecentsIcon;
        this.fromRecentsCoverColor = fromRecentsCoverColor;
        this.fromRecentsName = Objects.requireNonNull(fromRecentsName);
        this.fromRecentsIconColor = fromRecentsIconColor;
        this.defaultPlaylistAuthor = Objects.requireNonNull(defaultPlaylistAuthor);
        this.defaultPlaylistDescription = Objects.requireNonNull(defaultPlaylistDescription);
        this.playlists = playlists == null ? new ProxyPlaylistConfig[0] : playlists;
        getFromRecentsIcon();
        getFromRecentsCoverColor();
        getFromRecentsIconColor();
    }

    public ProxyVirtualLibConfig() {
        this(false, true, 30, "history", "#00ffff", "From your recent sessions", "#000000", "subsonic-analyzer",
                "Auto-generated by subsonic-analyzer", new ProxyPlaylistConfig[] {
                        new ProxyPlaylistConfig("Study mix", "study", "book_open", "#00ffff", 30, "#000000") });
    }

    public Color getFromRecentsIconColor() {
        return Color.decode(fromRecentsIconColor);
    }

    public Color getFromRecentsCoverColor() {
        return Color.decode(fromRecentsCoverColor);
    }

    public String getFromRecentsIcon() {
        return fromRecentsIcon == null ? null : FontAwesomeIcons.getIcon(fromRecentsIcon).orElseThrow();
    }
}
