package io.github.defective4.audioanalyzer.config;

import java.awt.Color;
import java.util.List;

import io.github.defective4.audioanalyzer.util.FontAwesomeIcons;

public record ProxyVirtualLibConfig(boolean enableVirtualLibrary, boolean generateFromRecents, int fromRecentsLimit,
        String fromRecentsIcon, String fromRecentsCoverColor, String fromRecentsName, String fromRecentsIconColor,
        List<ProxyPlaylistConfig> playlists, String defaultPlaylistAuthor, String defaultPlaylistDescription) {
    public ProxyVirtualLibConfig() {
        this(true, true, 30, "history", "#00ffff", "From your recent sessions", "#000000", List.of(), "test",
                "Auto-generated by subsonic-analyzer");
        getFromRecentsIcon();
        getFromRecentsCoverColor();
        getFromRecentsIconColor();
    }

    public Color getFromRecentsIconColor() {
        return Color.decode(fromRecentsIconColor);
    }

    public Color getFromRecentsCoverColor() {
        return Color.decode(fromRecentsCoverColor);
    }

    public String getFromRecentsIcon() {
        return fromRecentsIcon == null ? null : FontAwesomeIcons.getIcon(fromRecentsIcon).orElseThrow();
    }
}
