package io.github.defective4.audioanalyzer.config;

import java.awt.Color;

import io.github.defective4.audioanalyzer.util.FontAwesomeIcons;

public record ProxyVirtualLibConfig(boolean enableVirtualLibrary, boolean generateFromRecents, int fromRecentsLimit,
        String fromRecentsIcon, String fromRecentsCoverColor, String fromRecentsName, String fromRecentsIconColor,
        String defaultPlaylistAuthor, String defaultPlaylistDescription, ProxyPlaylistConfig[] playlists) {
    public ProxyVirtualLibConfig() {
        this(false, true, 30, "history", "#00ffff", "From your recent sessions", "#000000", "subsonic-analyzer",
                "Auto-generated by subsonic-analyzer", new ProxyPlaylistConfig[] {
                        new ProxyPlaylistConfig("Study mix", "study", "book_open", "#00ffff", 30, "#000000") });
        getFromRecentsIcon();
        getFromRecentsCoverColor();
        getFromRecentsIconColor();
    }

    public Color getFromRecentsIconColor() {
        return Color.decode(fromRecentsIconColor);
    }

    public Color getFromRecentsCoverColor() {
        return Color.decode(fromRecentsCoverColor);
    }

    public String getFromRecentsIcon() {
        return fromRecentsIcon == null ? null : FontAwesomeIcons.getIcon(fromRecentsIcon).orElseThrow();
    }
}
